// <auto-generated />
using System;
using EcommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524133021_NewMigrationAfterFix")]
    partial class NewMigrationAfterFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Electronic devices and gadgets",
                            ImageUrl = "/images/categories/electronics.jpg",
                            Name = "Electronics"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fashion and apparel",
                            ImageUrl = "/images/categories/clothes.jpg",
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Smart gadgets and accessories",
                            ImageUrl = "/images/categories/gadgets.jpg",
                            Name = "Gadgets"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Bags, watches and accessories",
                            ImageUrl = "/images/categories/accessories.jpg",
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Smart watches and wearables",
                            ImageUrl = "/images/categories/smartwatches.jpg",
                            Name = "Smart Watches"
                        });
                });

            modelBuilder.Entity("EcommerceApp.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StripePaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceApp.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("int");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "ArseMarket",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 407, DateTimeKind.Utc).AddTicks(1374),
                            Description = "High quality t-shirt available in multiple colors. Perfect for everyday wear. Made from premium cotton blend for comfort and durability.",
                            ImageUrl = "/images/products/product-1.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "T-Shirts with multiple colors, for men",
                            OldPrice = 16.00m,
                            Price = 10.30m,
                            Rating = 4.5,
                            ReviewCount = 154,
                            ShortDescription = "Size medium, Color: blue, Material: Plastic",
                            Stock = 150
                        },
                        new
                        {
                            Id = 2,
                            Brand = "ArseMarket",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1258),
                            Description = "Spacious and stylish backpack made from premium denim. Multiple compartments for all your storage needs.",
                            ImageUrl = "/images/products/product-2.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Solid Backpack blue jeans large size",
                            Price = 79.99m,
                            Rating = 4.2000000000000002,
                            ReviewCount = 98,
                            ShortDescription = "Large size, Color: blue, Denim material",
                            Stock = 60
                        },
                        new
                        {
                            Id = 3,
                            Brand = "KitchenPro",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1280),
                            Description = "Powerful 1200W electric water boiler with auto shutoff. Perfect for kitchen use. BPA-free interior with 360-degree swivel base.",
                            ImageUrl = "/images/products/product-3.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Water Boiler Black for Kitchen 1200 Watt",
                            Price = 79.99m,
                            Rating = 4.0,
                            ReviewCount = 77,
                            ShortDescription = "1200W, Color: Black, Fast boiling",
                            Stock = 45
                        },
                        new
                        {
                            Id = 4,
                            Brand = "FashionHub",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1287),
                            Description = "Stylish resort shirt perfect for summer. Breathable fabric with vibrant prints. Available in multiple sizes.",
                            ImageUrl = "/images/products/product-4.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Regular Fit Resort Shirt",
                            OldPrice = 85.00m,
                            Price = 57.70m,
                            Rating = 4.7000000000000002,
                            ReviewCount = 210,
                            ShortDescription = "Regular fit, Resort style, Multiple colors",
                            Stock = 200
                        },
                        new
                        {
                            Id = 5,
                            Brand = "GoPro",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1293),
                            Description = "Capture your adventures in stunning 4K. Waterproof to 33ft. Comes with voice control and image stabilization.",
                            ImageUrl = "/images/products/product-5.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "GoPro HERO6 4K Action Camera - Black",
                            OldPrice = 129.00m,
                            Price = 99.50m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 340,
                            ShortDescription = "4K, Waterproof, Action camera",
                            Stock = 30
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Canon",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1299),
                            Description = "Entry-level DSLR camera with 24.1 megapixel CMOS sensor. Built-in Wi-Fi and NFC for easy sharing.",
                            ImageUrl = "/images/products/product-6.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Canon EOS 2000D DSLR Camera",
                            Price = 998.00m,
                            Rating = 4.5999999999999996,
                            ReviewCount = 89,
                            ShortDescription = "24.1 MP, DSLR, Black",
                            Stock = 15
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Apple",
                            CategoryId = 5,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1304),
                            Description = "Advanced smartwatch with health monitoring, GPS, and seamless iPhone integration. All-day battery life.",
                            ImageUrl = "/images/products/product-7.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Apple Watch Series Smart Watch",
                            OldPrice = 350.00m,
                            Price = 299.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 520,
                            ShortDescription = "GPS, Heart rate, Fitness tracker",
                            Stock = 50
                        },
                        new
                        {
                            Id = 8,
                            Brand = "SoundMax",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1312),
                            Description = "Premium over-ear headphones with active noise cancellation. Crystal clear sound with deep bass. 30 hours playtime.",
                            ImageUrl = "/images/products/product-8.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "Wireless Noise-Cancelling Headphones",
                            OldPrice = 99.00m,
                            Price = 77.00m,
                            Rating = 4.4000000000000004,
                            ReviewCount = 185,
                            ShortDescription = "Wireless, ANC, 30hr battery",
                            Stock = 80
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1318),
                            Description = "The most advanced iPhone ever. A16 Bionic chip, 48MP camera system, and Dynamic Island.",
                            ImageUrl = "/images/products/product-9.jpg",
                            IsActive = true,
                            IsFeatured = true,
                            Name = "iPhone 14 Pro 256GB Space Black",
                            OldPrice = 1099.00m,
                            Price = 999.00m,
                            Rating = 4.9000000000000004,
                            ReviewCount = 650,
                            ShortDescription = "256GB, 5G, A16 Bionic chip",
                            Stock = 25
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Apple",
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 5, 24, 13, 30, 16, 408, DateTimeKind.Utc).AddTicks(1324),
                            Description = "Supercharged by M2 chip. Up to 20 hours battery life. Stunning Liquid Retina display.",
                            ImageUrl = "/images/products/product-10.jpg",
                            IsActive = true,
                            IsFeatured = false,
                            Name = "Laptop MacBook Pro 13 inch M2",
                            OldPrice = 1499.00m,
                            Price = 1299.00m,
                            Rating = 4.7999999999999998,
                            ReviewCount = 290,
                            ShortDescription = "M2 chip, 256GB SSD, 8GB RAM",
                            Stock = 20
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EcommerceApp.Models.OrderItem", b =>
                {
                    b.HasOne("EcommerceApp.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceApp.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceApp.Models.Product", b =>
                {
                    b.HasOne("EcommerceApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcommerceApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EcommerceApp.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceApp.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
